/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
// @ts-nocheck

import { Storage } from "../../../core/storage.js";
import { CONSTANTS } from "../../../core/constants.js";
import { createDebugger } from "../../../lib/debug.js";
import { getPagesHtml, getRepoReadme } from "./pages-template.js";
import { getCommitHistory, getContents } from "./api-client.js";
import { DEFAULT_THEME, getThemePalette } from "../../../core/theme-engine.js";

const dbg = createDebugger("GitHubInfra");

/**
 * GitHub infrastructure builder.
 * Generates repository configuration files, GitHub Actions, Pages templates.
 */

/**
 * Build list of infrastructure files to commit.
 * isNewRepo: true for initial repo setup, false for regular commits
 */
export async function buildInfraFiles(
    owner,
    repo,
    branch,
    token,
    settings,
    isNewRepo = false,
) {
    const items = [];

    // Get theme for Pages styling
    const theme = await Storage.getTheme().catch(() => null);
    const pagesTheme = _buildPagesTheme(theme);

    // GitHub Pages dashboard
    if (settings?.github_pages !== false) {
        const pageContent = await _buildPagesContent(
            owner,
            repo,
            token,
            pagesTheme,
            settings,
        );
        items.push({
            path: "index.html",
            mode: "100644",
            type: "blob",
            content: pageContent,
        });
    }

    // README.md — generated by extension, no GitHub Actions needed
    const pagesUrl =
        settings?.github_pages_url ||
        `https://${owner}.github.io/${repo}/`;
    const indexMeta = await _readIndexMeta(owner, repo, token).catch(() => null);
    items.push({
        path: "README.md",
        mode: "100644",
        type: "blob",
        content: getRepoReadme(owner, repo, pagesUrl, pagesTheme, settings, indexMeta),
    });

    // LICENSE (Apache-2.0)
    const currentYear = new Date().getFullYear();
    const licenseText = `Copyright ${currentYear} CodeLedger contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.`;

    items.push({
        path: "LICENSE",
        mode: "100644",
        type: "blob",
        content: licenseText,
    });

    // .gitignore
    items.push({
        path: ".gitignore",
        mode: "100644",
        type: "blob",
        content: `node_modules/
.env
.env.local
dist/
build/
*.log
.DS_Store
`,
    });

    // .codeledger/config.json — config placeholder (actual data may be in settings sync)
    items.push({
        path: ".codeledger/config.json",
        mode: "100644",
        type: "blob",
        content: JSON.stringify({
            version: "1.0",
            extension: "CodeLedger",
            createdAt: new Date().toISOString(),
            settings: {},
        }, null, 2),
    });

    return items;
}

/**
 * Build Pages HTML with optional commit verification and images.
 */
async function _buildPagesContent(
    owner,
    repo,
    token,
    pagesTheme,
    settings,
) {
    let commitSummary = null;
    let commitList = [];
    let reportImages = [];

    try {
        if (settings.pages_show_verification) {
            const commits = await getCommitHistory(owner, repo, { per_page: 20 }, token);
            const rawList = Array.isArray(commits) ? commits : commits?.data || [];
            const total = rawList.length;
            const verified = rawList.filter((c) => c?.commit?.verification?.verified)
                .length;

            commitSummary = { total, verified };
            commitList = rawList.slice(0, 20).map((c) => ({
                sha: c.sha,
                url:
                    c.html_url ||
                    (c?.url ? `https://github.com/${owner}/${repo}/commit/${c.sha}` : ""),
                message: c.commit?.message?.split("\n")[0] || "",
                author: c.author?.login || c.commit?.author?.name || "",
                verified: !!(c.commit?.verification?.verified),
            }));

            dbg.log("Commit verification summary fetched");
        }
    } catch (e) {
        dbg.warn("Failed to fetch commit summary:", e.message);
    }

    try {
        const imgs = await getCommitHistory(
            owner,
            repo,
            { path: "report-images" },
            token,
        ).catch(() => null);
        if (imgs?.data) {
            reportImages = imgs.data
                .filter((i) => i.type === "file")
                .map((i) => i.path);
        }
    } catch (_) {
        // Ignore if folder missing
    }

    return getPagesHtml({
        theme: pagesTheme,
        settings,
        commitSummary,
        reportImages,
        commitList,
    });
}

/**
 * Build theme object for Pages styling.
 */
function _buildPagesTheme(theme = null) {
    const base = { ...DEFAULT_THEME, ...(theme || {}) };
    const darkPalette = getThemePalette({ ...base, mode: "dark" });
    const lightPalette = getThemePalette({ ...base, mode: "light" });

    return {
        mode: base.mode || "dark",
        preset: base.preset || "material-dark",
        dark: {
            bg: darkPalette["bg-primary"],
            surface: darkPalette["bg-secondary"] || darkPalette["bg-primary"],
            border: darkPalette["border-color"] || "rgba(255,255,255,.08)",
            text: darkPalette["text-primary"],
            muted: darkPalette["text-muted"] || darkPalette["text-secondary"],
            accent: darkPalette["primary-color"],
        },
        light: {
            bg: lightPalette["bg-primary"],
            surface: lightPalette["bg-secondary"] || lightPalette["bg-primary"],
            border: lightPalette["border-color"] || "rgba(15,23,42,.12)",
            text: lightPalette["text-primary"],
            muted: lightPalette["text-muted"] || lightPalette["text-secondary"],
            accent: lightPalette["primary-color"],
        },
    };
}

/**
 * Fetch meta fields (stats, summary, topTopics) from repo's index.json.
 * Used to build an expansive README without re-computing from local storage.
 */
async function _readIndexMeta(owner, repo, token) {
    try {
        const file = await getContents(owner, repo, "index.json", token);
        if (!file?.content) return null;
        const raw = atob(file.content.replace(/\n/g, ""));
        const parsed = JSON.parse(raw);
        return {
            stats: parsed.stats || null,
            summary: parsed.meta?.summary || null,
            updatedAt: parsed.updatedAt || null,
            problems: (parsed.problems || []).slice(0, 10),
        };
    } catch (_) {
        return null;
    }
}

/**
 * Normalize and resolve repository topics.
 */
export function resolveRepoTopics(settings = {}) {
    const DEFAULT_TOPICS = [
        "codeledger",
        "dsa",
        "leetcode",
        "algorithms",
        "dynamic-programming",
        "graphs",
        "trees",
        "arrays",
        "hashing",
        "greedy",
    ];

    const extras = String(settings.github_repo_topics_extra || "")
        .split(",")
        .map((s) => _normalizeTopic(s))
        .filter(Boolean);

    const merged = [...new Set([...DEFAULT_TOPICS, ...extras])];
    return merged.slice(0, 20);
}

/**
 * Normalize a single topic.
 */
function _normalizeTopic(topic) {
    return String(topic || "")
        .trim()
        .toLowerCase()
        .replace(/\s+/g, "-")
        .replace(/[^a-z0-9-]/g, "")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
}
